name: Loan_prediction
channels:
  - defaults
dependencies:
- python=3.12.1
- pip<=23.2.1
- pip:
  - mlflow==2.13.0
  - cloudpickle==3.0.0
  - numpy==1.26.4
  - packaging==24.0
  - pyyaml==6.0.1
  - scikit-learn==1.5.0
  - scipy==1.13.1